set shell := ["bash", "-c"]

binary_extension := if os() == "windows" { ".exe" } else { "" }

default:
	just --list

# Run cargo-vcpkg build for SDL2 dependencies
vcpkg:
	VCPKG_OVERLAY_PORTS="{{justfile_directory()}}/vcpkg-overlay" cargo vcpkg build

# Profile using samply
samply:
    cargo build --profile profile
    samply record ./target/profile/pacman{{binary_extension}}

# Run with Tracy live profiling enabled (connect a Tracy GUI to 127.0.0.1)
tracy:
    cargo run --profile profile --features tracy

# Generate baseline LCOV report
coverage:
    cargo +nightly llvm-cov \
        --lcov \
        --remap-path-prefix \
        --workspace \
        --output-path lcov.info \
        --profile coverage \
        --no-fail-fast nextest

# Display coverage report
report-coverage: coverage
    cargo llvm-cov report --remap-path-prefix

# Open HTML coverage report
html: coverage
    cargo llvm-cov report \
        --remap-path-prefix \
        --html \
        --open
