repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-toml
      - id: check-yaml
      - id: forbid-submodules
      - id: mixed-line-ending

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []

  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --all --
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-check
        name: cargo check
        entry: cargo check --workspace --all-targets
        language: system
        types_or: [rust, cargo, cargo-lock]
        pass_filenames: false

      - id: cargo-check-wasm
        name: cargo check for wasm32-unknown-emscripten
        entry: cargo check -p pacman --all-targets --target=wasm32-unknown-emscripten
        language: system
        types_or: [rust, cargo, cargo-lock]
        pass_filenames: false
