[profile.default]
fail-fast = false
slow-timeout = { period = "5s", terminate-after = 3 } # max 15 seconds
retries = 1

# CI machines are pretty slow, so we need to increase the timeout
[profile.ci]
slow-timeout = { period = "30s", terminate-after = 4 } # max 2 minutes for slow tests

# Coverage works even slower, so we need to increase the timeout
[profile.coverage]
slow-timeout = { period = "45s", terminate-after = 5 } # max 3.75 minutes for slow tests
status-level = "none"

# Integration tests in SDL2 run serially (may not be required)
[[profile.default.overrides]]
filter = 'test(pacman::game::)'
test-group = 'serial'

# Integration tests run max 4 at a time
[[profile.default.overrides]]
filter = 'test(pacman-server::tests::oauth)'
test-group = 'integration'

[test-groups]
# Ensure serial tests don't run in parallel
serial = { max-threads = 1 }
integration = { max-threads = 4 }
