[profile.default]
fail-fast = false
slow-timeout = { period = "5s", terminate-after = 6 }

[profile.coverage]
status-level = "none"

[[profile.default.overrides]]
filter = 'test(pacman::game::)'
test-group = 'serial'

[test-groups]
serial = { max-threads = 1 }
