name: Builds

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build (${{ matrix.target }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: pacman
          - os: macos-15-intel
            target: x86_64-apple-darwin
            artifact_name: pacman
          - os: macos-15
            target: aarch64-apple-darwin
            artifact_name: pacman
          - os: windows-latest
            target: x86_64-pc-windows-gnu
            artifact_name: pacman.exe
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Rust Toolchain
        uses: mkroening/rust-toolchain-toml@main

      - name: Add target
        run: rustup target add ${{ matrix.target }}

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Setup vcpkg
        uses: ./.github/actions/vcpkg-setup
        with:
          target: ${{ matrix.target }}

      - name: Build
        run: cargo build --release
        working-directory: pacman

      - name: Acquire Package Version
        id: get_version
        shell: bash # required to prevent Windows runners from failing
        run: |
          set -euo pipefail # exit on error
          echo "version=$(cargo metadata --format-version 1 --no-deps | jq '.packages[0].version' -r)" >> $GITHUB_OUTPUT
        working-directory: pacman

      - name: Upload Artifact
        uses: actions/upload-artifact@v5
        with:
          name: "pacman-${{ steps.get_version.outputs.version }}-${{ matrix.target }}"
          path: ./target/release/${{ matrix.artifact_name }}
          retention-days: 7
          if-no-files-found: error
