name: Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Rust toolchain
        uses: mkroening/rust-toolchain-toml@main

      - name: Add wasm target
        run: rustup target add wasm32-unknown-emscripten

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Setup vcpkg
        uses: ./.github/actions/vcpkg-setup

      - name: Run clippy (desktop)
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings

      - name: Run clippy (wasm)
        run: cargo clippy -p pacman --target wasm32-unknown-emscripten --all-targets --all-features -- -D warnings

      - name: Check formatting
        run: cargo fmt --all -- --check

      - uses: taiki-e/install-action@cargo-audit

      - name: Run security audit
        run: cargo audit
