name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Rust toolchain
        uses: mkroening/rust-toolchain-toml@main

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Setup vcpkg
        uses: ./.github/actions/vcpkg-setup

      - uses: taiki-e/install-action@nextest

      - name: Run nextest
        run: cargo nextest run --workspace --profile ci
        working-directory: pacman
