name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Install Rust toolchain
        uses: mkroening/rust-toolchain-toml@efdebac439b4b9a6c5de2df55452c21faa37420f # main

      - name: Rust Cache
        uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2

      - name: Setup vcpkg
        uses: ./.github/actions/vcpkg-setup

      - uses: taiki-e/install-action@11c82bec3ad7f6041db8bd552d47469a973381cd # nextest

      - name: Run nextest
        run: cargo nextest run --workspace --profile ci
        working-directory: pacman
